name: scalaz-task-effect
baseurl: /scalaz-task-effect
description: Cats Instances for Scalaz Task
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.2-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
